services:
  postgres:
    container_name: dogokit-corgi-postgres
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    env_file:
      - path: .env
        required: true
  app:
    container_name: dogokit-corgi-app
    image: dogokit-corgi:latest
    build:
      context: .
    ports:
      - ${PORT}:3000
    depends_on:
      - postgres
    env_file:
      - path: .env.prod
        required: true

volumes:
  postgres_data:
