services:
  postgres:
    container_name: dogokit-corgi-postgres
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - "50000:5432"
    env_file:
      - path: .env
        required: true
  app:
    container_name: dogokit-corgi-app
    image: dogokit-corgi:latest
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - path: .env
        required: true

volumes:
  postgres_data:
