services:
  postgres:
    container_name: dogokit-corgi-postgres
    image: postgres:alpine
    restart: no
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    env_file:
      - path: .env
        required: true

volumes:
  postgres_data:
